image: docker:stable
stages:
  - package
  - docker_build
  - deploy_k8s
mvn_build_job:
  image: maven:3.6.2-jdk-14
  stage: package
  tags:
    - k8s-runner
  script:
    - mvn package -DskipTests
    - cp target/*.jar /opt/cache
docker_build_job:
  image: docker:latest
  stage: docker_build
  tags:
    - k8s-runner
  script:
    - docker login -u admin -p admin 127.0.0.1:5000
    - mkdir target
    - cp /opt/cache/*.jar target/
    - docker build -t 127.0.0.1:5000/demo .
    - docker push 127.0.0.1:5000/demo
deploy_k8s_job:
  stage: deploy_k8s
  tags:
    - k8s-runner
  script:
    - sed -i "s~127.0.0.1:5000/demo~g" deployment.yaml
    - kubectl apply -f deployment.yaml