kind: Service
apiVersion: v1
metadata:
  name: demo-student
  namespace: demo
spec:
  selector:
    app: demo-student
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-student
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo-student
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-student
    spec:
      containers:
        - name: demo-student
          image: 127.0.0.1:5000/demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080